[package]
name = "adaptive_cards_host_config"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
serde = { workspace = true, features = ["derive"] }

[build-dependencies]
populate_schema_defaults = { path = "../populate_schema_defaults" }
