[workspace]
members = [
    "slipway-render-component",
    "slipway-theme-component",
    "slipway-modify-component",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["James Thurley"]

[workspace.dependencies]
