[package]
name = "slipway-theme-component"
version = "0.1.0"
edition.workspace = true
authors.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
serde_json = "1.0.104"
serde = { version = "1.0.180", features = ["derive"] }
