[package]
name = "slipway-renderer"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }

[build-dependencies]
ac-types-generator = { path = "../ac-types-generator" }