[package]
name = "slipway-renderer"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]

[build-dependencies]
ac-types-generator = { path = "../ac-types-generator" }